# Generated by Django 5.2.5 on 2025-09-11 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_userprofile_user_profile_delete_community_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text="e.g., 'fas fa-leaf'", max_length=50)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='bronze', max_length=10)),
                ('condition_key', models.CharField(help_text='A unique key for the unlocking logic', max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='carbon_budget_kg',
            field=models.FloatField(default=500.0, help_text="User's personal monthly CO2 budget in kg"),
        ),
        migrations.AlterField(
            model_name='activity',
            name='unit',
            field=models.CharField(help_text="e.g., 'km', 'kWh', 'serving'", max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='value',
            field=models.FloatField(help_text='e.g., distance in km, energy in kWh, quantity of items'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, help_text='e.g., Mumbai, India', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_earned', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
